### PR TITLE
Refactor/refactor server js

### PR DESCRIPTION
**Pull request by RandomSeeded**
Refactor server.js into 4 separate files: server.js, chatHandler.js, socketHandler.js, and playlistHandler.js.

Functionality should be unchanged, all tests are passing, at least locally.

Other things to note: 
- Global variables (e.g. youtubeKey) are now module variables on the server.js module, with the exception of the following:
- Global variables that are going to be changed/read in multiple places (playlist and messages) now have getters & setters for cleanliness
- I placed a few constants (playlist refresh time, youtube search results) into configuration variables

### CODE REVIEW

**Comment by RandomSeeded** [comment]
Wooo travis ^_^

**Comment by csling** [comment]
Nate, great job on the refactoring.  Splitting up the functionality definitely helps make our code easier to understand. I think the only suggestion I'd make is having a separate "youtubeUtility.js" file, or something similar for all the functions which directly use the Youtube API.  Let me know what you think!

**Comment by RandomSeeded** [comment]
Yeah that makes total sense to me. Is there anything you'd want in there that we already have written other than the fetchPlaylistFromYoutube function? The other potential component I'm seeing would be the https.get currently in playSong in the playlist handler; we could totally split out the playSong function into two.

**Comment by csling** [comment]
Looking good! I totally agree on abstracting the https.get request for song info into another YT utility function.  I'm going to merge.

**Pull request merged**
