### PR TITLE
Implement front end/HTML for chat client and...

### PR DESCRIPTION
**Pull request by yx296**
Cleaned up some code, 
set up basic Chat client/server functionality using sockets, unfortunately the messages are being delayed in the client, but show up instantly in server from the console.log on line 63.

https://scontent-sjc2-1.xx.fbcdn.net/hphotos-xft1/t31.0-8/12010542_3300909809836_872563025957285910_o.jpg

Not sure what is going on, maybe Nate knows whats up

@csling 
@xerxesv 
@RandomSeeded

### CODE REVIEW

**Comment by RandomSeeded** [comment]
I'll take a look and see what I can see

**Comment by RandomSeeded** [comment]
Heyo! Looks good dude. A few minor things

1) Server-side, there's no need to have two separate functions for socket.on('chat message'), let's combine them into one (or possibly remove the console.log one entirely if it was just for debugging?)

2) Found the issue with client-side delay in rendering. Angular doesn't know that $scope.messages got modified, b/c it wasn't initiated by an angular listener. Easy enough to fix, we just tack on $scope.$apply at the end of the 'chat message' listener on the client-side

3) I think we want to include usernames as well. Do we want to take care of that right now or in a subsequent pull request?

4) Also tests please, though that's chillin in a subsequent pull request as well? (Thoughts dudes? Are we trying to include tests with every pull req to make sure they get done?)

Thanks for this though, I think this was the biggest outstanding thing we had to do and it looks fantastic

**Comment by yx296** [comment]
Maybe a subsequent pull request, since I'll have to learn how to write tests for this, that was the one part I messed up on the summary assessment. 

I wasn't sure how we wanted the username functionality to look like--- just a input where people can supply a username? Will they be allowed to chat if they don't give one, etc. maybe we can talk about that on tuesday.

Nice finding the $scope.$apply! So how does this pull request update thing work, I just add in the $scope.$apply and combine the two socket.on functions, commit, then push to my branch, and the pull request gets automatically updated?

**Comment by RandomSeeded** [comment]
Sounds good on all counts. As far as the pull request update goes, I'm not entirely sure (haven't tried it yet), but yeah I think that's correct.

**Comment by yx296** [comment]
$scope.apply now working with factory, I think the pull request got updated too. 
The messages are snappy as they should be on the client side.

**Comment by RandomSeeded** [comment]
Merging! 

As a heads up, if at some point in time we change the architecture such that we loaded the controller multiple times, we do need to be aware that this would cause multiple listeners to be added for each event. Check out here for more: http://stackoverflow.com/questions/14389049/improve-this-angularjs-factory-to-use-with-socket-io

I think with our current architecture we'll never load a controller more than once though, so we shouldn't run into that

**Pull request merged**
