### PR TITLE
Feat/chat bang handling

### PR DESCRIPTION
**Pull request by yx296**
Code cleanup, Add chat bang results to playlist.

### CODE REVIEW

**Comment by yx296** [comment]
Hey Christian, we're leaving this up as an open pull req so you can take a look at it; I think YiLin and I are both planning to do additional work possibly as early as tonight so we may merge it in shortly regardless. We worked together/had two eyes on this.

-Nate

**Comment by csling** [comment]
Thanks for the heads up. Taking a look right now.  I'm looking at the Travis build log and the environmental variables are missing--I think there might be an issue again with the .travis.yml file not being a part of the pull request.

**Comment by csling** [comment]
There's a duplicate currentSong (see 32 and 39).  Otherwise I think it makes sense.  Good work guys!

**Comment by RandomSeeded** [comment]
Good catch, thanks Christian. Yilin, I can't edit your pull req, so this is all you dude @yx296

**Comment by yx296** [comment]
Yeah just having some git issues, we worked on a work station at Hack Reactor instead of my laptop, so I was unsure how to grab the branch we made there, I can close this one and make a new pull request with the excess duplicate currentSong taken out if need be

**Pull request closed without merging**
